services:
  - type: web
    name: infotess-sdms
    env: php
    plan: free
    buildCommand: composer install
    startCommand: apache2-foreground
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
